//! Static asset serving for the embedded web UI.
//!
//! Assets are embedded at compile time from the `dist/` directory
//! (built by `cd crates/ui/frontend && npm run build`).
//! The build.rs script generates the asset list dynamically so
//! hashed filenames from Vite don't need to be hardcoded.

use axum::{
    http::{header, StatusCode, Uri},
    response::{Html, IntoResponse, Response},
};

// Generated by build.rs: INDEX_HTML and ASSETS array
include!(concat!(env!("OUT_DIR"), "/embedded_assets.rs"));

/// Serve static files for the web UI.
///
/// Routes:
/// - `/assets/*` → matched embedded asset files
/// - Everything else → index.html (SPA client-side routing fallback)
pub async fn static_handler(uri: Uri) -> Response {
    let path = uri.path();

    // Serve asset files from /assets/
    if path.starts_with("/assets/") {
        let filename = &path["/assets/".len()..];
        for (name, content_type, bytes) in ASSETS {
            if *name == filename {
                return (
                    StatusCode::OK,
                    [
                        (header::CONTENT_TYPE, *content_type),
                        (header::CACHE_CONTROL, "public, max-age=31536000, immutable"),
                    ],
                    *bytes,
                )
                    .into_response();
            }
        }
        return StatusCode::NOT_FOUND.into_response();
    }

    // Everything else gets the SPA index.html
    Html(INDEX_HTML).into_response()
}
