// Thin WebRTC peer wrapper. Opens mic, announces, sends SDP offer,
// collects ICE. Surfaces remote audio track through `onRemoteTrack`.

import type { SignalingClient } from './signaling'

export interface PeerAnnounceResult {
  success: boolean
  peer_id: string
  peers_count: number
  other_peers: string[]
}

export interface PeerAnswerResult {
  type: 'answer'
  sdp: string
  from: string
  to: string
}

const SERVER_PEER = 'remotemedia-server'

export class WebRtcPeer {
  private pc: RTCPeerConnection | null = null
  private ws: SignalingClient
  private peerId: string
  private iceCandidateQueue: RTCIceCandidateInit[] = []
  private remoteDescriptionSet = false
  /// Outbound ICE candidates generated by our own PC before the server
  /// has created its `ServerPeer` (which only happens once `peer.offer`
  /// has been processed). Sending them early races the ServerPeer
  /// creation and they get silently dropped — buffer until the offer
  /// response arrives, then flush.
  private outboundIceQueue: RTCIceCandidateInit[] = []
  private serverPeerReady = false
  private onRemoteTrack?: (track: MediaStreamTrack, streams: MediaStream[]) => void
  private onStateChange?: (state: RTCPeerConnectionState) => void
  private offNotif: (() => void) | null = null

  constructor(ws: SignalingClient, peerId: string) {
    this.ws = ws
    this.peerId = peerId
  }

  setCallbacks(cbs: {
    onRemoteTrack?: (track: MediaStreamTrack, streams: MediaStream[]) => void
    onStateChange?: (state: RTCPeerConnectionState) => void
  }) {
    this.onRemoteTrack = cbs.onRemoteTrack
    this.onStateChange = cbs.onStateChange
  }

  getPeerId() {
    return this.peerId
  }

  async connect(localStream: MediaStream): Promise<void> {
    // Announce first so the server knows who we are.
    await this.ws.call<PeerAnnounceResult>('peer.announce', {
      peer_id: this.peerId,
      capabilities: ['audio'],
    })

    const pc = new RTCPeerConnection({
      iceServers: [{ urls: 'stun:stun.l.google.com:19302' }],
    })
    this.pc = pc

    // Register server-originated ICE + answer handlers. Server sends
    // `peer.ice_candidate` notifications (not request/response) with
    // from: remotemedia-server.
    this.offNotif = this.ws.onNotification(async (method, params) => {
      if (method === 'peer.ice_candidate') {
        const p = params as {
          from: string
          to: string
          candidate: string
          sdp_mid?: string | null
          sdp_m_line_index?: number | null
        }
        if (p.to !== this.peerId) return
        if (!p.candidate) return // end-of-candidates sentinel
        const init: RTCIceCandidateInit = {
          candidate: p.candidate,
          sdpMid: p.sdp_mid ?? undefined,
          sdpMLineIndex: p.sdp_m_line_index ?? undefined,
        }
        if (!this.remoteDescriptionSet) {
          this.iceCandidateQueue.push(init)
          return
        }
        try {
          await pc.addIceCandidate(init)
        } catch (e) {
          console.warn('[webrtc] addIceCandidate failed:', e)
        }
      } else if (method === 'peer.state_change') {
        // Purely informational; local onconnectionstatechange is the
        // truth source for the UI.
      }
    })

    pc.onconnectionstatechange = () => {
      this.onStateChange?.(pc.connectionState)
    }
    pc.ontrack = (ev) => {
      this.onRemoteTrack?.(ev.track, ev.streams as MediaStream[])
    }
    pc.onicecandidate = (ev) => {
      if (!ev.candidate) return
      const init: RTCIceCandidateInit = {
        candidate: ev.candidate.candidate,
        sdpMid: ev.candidate.sdpMid ?? undefined,
        sdpMLineIndex: ev.candidate.sdpMLineIndex ?? undefined,
      }
      if (!this.serverPeerReady) {
        this.outboundIceQueue.push(init)
        return
      }
      this.sendIce(init)
    }

    // Publish mic on a sendonly transceiver — the upstream LFM2
    // pipeline is the only audio consumer, we never need the browser
    // to receive its own mic back.
    for (const track of localStream.getAudioTracks()) {
      const tx = pc.addTransceiver(track, {
        direction: 'sendonly',
        streams: [localStream],
      })
      // Silence TS: `tx` is observable in chrome://webrtc-internals
      // but not referenced here.
      void tx
    }
    // Separate recvonly audio transceiver for the server's reply
    // stream. Without this, the SDP exposes only the mic m-line and
    // the browser has nowhere to demux inbound audio RTP — which
    // shows up in chrome://webrtc-internals as "no inbound-rtp".
    pc.addTransceiver('audio', { direction: 'recvonly' })
    pc.addTransceiver('video', { direction: 'recvonly' })

    // SDP exchange. The server returns the answer directly in the JSON-RPC
    // result for `peer.offer`.
    const offer = await pc.createOffer()
    await pc.setLocalDescription(offer)
    const result = await this.ws.call<PeerAnswerResult>('peer.offer', {
      from: this.peerId,
      to: SERVER_PEER,
      sdp: offer.sdp!,
    })
    // The ServerPeer now exists on the server side — it's safe to
    // forward any ICE candidates our PC has already produced.
    this.serverPeerReady = true
    for (const init of this.outboundIceQueue.splice(0)) {
      this.sendIce(init)
    }

    await pc.setRemoteDescription({ type: 'answer', sdp: result.sdp })
    this.remoteDescriptionSet = true
    // Drain any server ICE candidates that arrived before
    // setRemoteDescription.
    for (const init of this.iceCandidateQueue.splice(0)) {
      try {
        await pc.addIceCandidate(init)
      } catch (e) {
        console.warn('[webrtc] queued addIceCandidate failed:', e)
      }
    }
  }

  private sendIce(init: RTCIceCandidateInit) {
    this.ws
      .call('peer.ice_candidate', {
        from: this.peerId,
        to: SERVER_PEER,
        candidate: init.candidate,
        sdp_mid: init.sdpMid,
        sdp_m_line_index: init.sdpMLineIndex,
      })
      .catch((e) => console.warn('[webrtc] ice forward failed', e))
  }

  close() {
    this.offNotif?.()
    this.offNotif = null
    this.pc?.close()
    this.pc = null
  }
}
