from typing import Any

__version__: str

def execute_pipeline(manifest) -> Any: ...
def execute_pipeline_with_input(*args, **kwargs): ...
def execute_pipeline_with_instances(*args, **kwargs): ...
def get_runtime_version(*args, **kwargs): ...
def is_available(*args, **kwargs): ...
