# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import execution_pb2 as execution__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in execution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteExecutionServiceStub(object):
    """Remote Execution Service
    Provides secure, sandboxed execution of processing nodes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteNode = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/ExecuteNode',
                request_serializer=execution__pb2.ExecuteNodeRequest.SerializeToString,
                response_deserializer=execution__pb2.ExecuteNodeResponse.FromString,
                _registered_method=True)
        self.ExecuteCustomTask = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/ExecuteCustomTask',
                request_serializer=execution__pb2.ExecuteCustomTaskRequest.SerializeToString,
                response_deserializer=execution__pb2.ExecuteCustomTaskResponse.FromString,
                _registered_method=True)
        self.StreamNode = channel.stream_stream(
                '/remotemedia.execution.RemoteExecutionService/StreamNode',
                request_serializer=execution__pb2.StreamData.SerializeToString,
                response_deserializer=execution__pb2.StreamData.FromString,
                _registered_method=True)
        self.StreamObject = channel.stream_stream(
                '/remotemedia.execution.RemoteExecutionService/StreamObject',
                request_serializer=execution__pb2.StreamObjectRequest.SerializeToString,
                response_deserializer=execution__pb2.StreamObjectResponse.FromString,
                _registered_method=True)
        self.ExecuteObjectMethod = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/ExecuteObjectMethod',
                request_serializer=execution__pb2.ExecuteObjectMethodRequest.SerializeToString,
                response_deserializer=execution__pb2.ExecuteObjectMethodResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/GetStatus',
                request_serializer=execution__pb2.StatusRequest.SerializeToString,
                response_deserializer=execution__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/ListNodes',
                request_serializer=execution__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=execution__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.InitGenerator = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/InitGenerator',
                request_serializer=execution__pb2.InitGeneratorRequest.SerializeToString,
                response_deserializer=execution__pb2.InitGeneratorResponse.FromString,
                _registered_method=True)
        self.GetNextBatch = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/GetNextBatch',
                request_serializer=execution__pb2.GetNextBatchRequest.SerializeToString,
                response_deserializer=execution__pb2.GetNextBatchResponse.FromString,
                _registered_method=True)
        self.CloseGenerator = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/CloseGenerator',
                request_serializer=execution__pb2.CloseGeneratorRequest.SerializeToString,
                response_deserializer=execution__pb2.CloseGeneratorResponse.FromString,
                _registered_method=True)
        self.ExportTypeScriptDefinitions = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/ExportTypeScriptDefinitions',
                request_serializer=execution__pb2.ExportTypeScriptRequest.SerializeToString,
                response_deserializer=execution__pb2.ExportTypeScriptResponse.FromString,
                _registered_method=True)
        self.RegisterPipeline = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/RegisterPipeline',
                request_serializer=execution__pb2.RegisterPipelineRequest.SerializeToString,
                response_deserializer=execution__pb2.RegisterPipelineResponse.FromString,
                _registered_method=True)
        self.UnregisterPipeline = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/UnregisterPipeline',
                request_serializer=execution__pb2.UnregisterPipelineRequest.SerializeToString,
                response_deserializer=execution__pb2.UnregisterPipelineResponse.FromString,
                _registered_method=True)
        self.ListPipelines = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/ListPipelines',
                request_serializer=execution__pb2.ListPipelinesRequest.SerializeToString,
                response_deserializer=execution__pb2.ListPipelinesResponse.FromString,
                _registered_method=True)
        self.GetPipelineInfo = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/GetPipelineInfo',
                request_serializer=execution__pb2.GetPipelineInfoRequest.SerializeToString,
                response_deserializer=execution__pb2.GetPipelineInfoResponse.FromString,
                _registered_method=True)
        self.ExecutePipeline = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/ExecutePipeline',
                request_serializer=execution__pb2.ExecutePipelineRequest.SerializeToString,
                response_deserializer=execution__pb2.ExecutePipelineResponse.FromString,
                _registered_method=True)
        self.StreamPipeline = channel.stream_stream(
                '/remotemedia.execution.RemoteExecutionService/StreamPipeline',
                request_serializer=execution__pb2.StreamPipelineRequest.SerializeToString,
                response_deserializer=execution__pb2.StreamPipelineResponse.FromString,
                _registered_method=True)
        self.SavePipeline = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/SavePipeline',
                request_serializer=execution__pb2.SavePipelineRequest.SerializeToString,
                response_deserializer=execution__pb2.SavePipelineResponse.FromString,
                _registered_method=True)
        self.LoadPipeline = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/LoadPipeline',
                request_serializer=execution__pb2.LoadPipelineRequest.SerializeToString,
                response_deserializer=execution__pb2.LoadPipelineResponse.FromString,
                _registered_method=True)
        self.ListStoredPipelines = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/ListStoredPipelines',
                request_serializer=execution__pb2.ListStoredPipelinesRequest.SerializeToString,
                response_deserializer=execution__pb2.ListStoredPipelinesResponse.FromString,
                _registered_method=True)
        self.ClonePipeline = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/ClonePipeline',
                request_serializer=execution__pb2.ClonePipelineRequest.SerializeToString,
                response_deserializer=execution__pb2.ClonePipelineResponse.FromString,
                _registered_method=True)
        self.SaveNode = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/SaveNode',
                request_serializer=execution__pb2.SaveNodeRequest.SerializeToString,
                response_deserializer=execution__pb2.SaveNodeResponse.FromString,
                _registered_method=True)
        self.LoadNode = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/LoadNode',
                request_serializer=execution__pb2.LoadNodeRequest.SerializeToString,
                response_deserializer=execution__pb2.LoadNodeResponse.FromString,
                _registered_method=True)
        self.ListStoredNodes = channel.unary_unary(
                '/remotemedia.execution.RemoteExecutionService/ListStoredNodes',
                request_serializer=execution__pb2.ListStoredNodesRequest.SerializeToString,
                response_deserializer=execution__pb2.ListStoredNodesResponse.FromString,
                _registered_method=True)


class RemoteExecutionServiceServicer(object):
    """Remote Execution Service
    Provides secure, sandboxed execution of processing nodes
    """

    def ExecuteNode(self, request, context):
        """Execute a predefined SDK node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCustomTask(self, request, context):
        """Execute user-defined code (Phase 3)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamNode(self, request_iterator, context):
        """Bidirectional streaming for real-time processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamObject(self, request_iterator, context):
        """Bidirectional streaming for serialized objects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteObjectMethod(self, request, context):
        """Execute a method on a serialized object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get service status and health information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """List available SDK nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitGenerator(self, request, context):
        """Generator streaming support
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseGenerator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportTypeScriptDefinitions(self, request, context):
        """Export TypeScript interface definitions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPipeline(self, request, context):
        """Pipeline management services
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPipelines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPipelineInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPipeline(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SavePipeline(self, request, context):
        """Persistence operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStoredPipelines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClonePipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveNode(self, request, context):
        """Node persistence operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStoredNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteNode,
                    request_deserializer=execution__pb2.ExecuteNodeRequest.FromString,
                    response_serializer=execution__pb2.ExecuteNodeResponse.SerializeToString,
            ),
            'ExecuteCustomTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCustomTask,
                    request_deserializer=execution__pb2.ExecuteCustomTaskRequest.FromString,
                    response_serializer=execution__pb2.ExecuteCustomTaskResponse.SerializeToString,
            ),
            'StreamNode': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamNode,
                    request_deserializer=execution__pb2.StreamData.FromString,
                    response_serializer=execution__pb2.StreamData.SerializeToString,
            ),
            'StreamObject': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamObject,
                    request_deserializer=execution__pb2.StreamObjectRequest.FromString,
                    response_serializer=execution__pb2.StreamObjectResponse.SerializeToString,
            ),
            'ExecuteObjectMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteObjectMethod,
                    request_deserializer=execution__pb2.ExecuteObjectMethodRequest.FromString,
                    response_serializer=execution__pb2.ExecuteObjectMethodResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=execution__pb2.StatusRequest.FromString,
                    response_serializer=execution__pb2.StatusResponse.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=execution__pb2.ListNodesRequest.FromString,
                    response_serializer=execution__pb2.ListNodesResponse.SerializeToString,
            ),
            'InitGenerator': grpc.unary_unary_rpc_method_handler(
                    servicer.InitGenerator,
                    request_deserializer=execution__pb2.InitGeneratorRequest.FromString,
                    response_serializer=execution__pb2.InitGeneratorResponse.SerializeToString,
            ),
            'GetNextBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextBatch,
                    request_deserializer=execution__pb2.GetNextBatchRequest.FromString,
                    response_serializer=execution__pb2.GetNextBatchResponse.SerializeToString,
            ),
            'CloseGenerator': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseGenerator,
                    request_deserializer=execution__pb2.CloseGeneratorRequest.FromString,
                    response_serializer=execution__pb2.CloseGeneratorResponse.SerializeToString,
            ),
            'ExportTypeScriptDefinitions': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportTypeScriptDefinitions,
                    request_deserializer=execution__pb2.ExportTypeScriptRequest.FromString,
                    response_serializer=execution__pb2.ExportTypeScriptResponse.SerializeToString,
            ),
            'RegisterPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPipeline,
                    request_deserializer=execution__pb2.RegisterPipelineRequest.FromString,
                    response_serializer=execution__pb2.RegisterPipelineResponse.SerializeToString,
            ),
            'UnregisterPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterPipeline,
                    request_deserializer=execution__pb2.UnregisterPipelineRequest.FromString,
                    response_serializer=execution__pb2.UnregisterPipelineResponse.SerializeToString,
            ),
            'ListPipelines': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPipelines,
                    request_deserializer=execution__pb2.ListPipelinesRequest.FromString,
                    response_serializer=execution__pb2.ListPipelinesResponse.SerializeToString,
            ),
            'GetPipelineInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPipelineInfo,
                    request_deserializer=execution__pb2.GetPipelineInfoRequest.FromString,
                    response_serializer=execution__pb2.GetPipelineInfoResponse.SerializeToString,
            ),
            'ExecutePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePipeline,
                    request_deserializer=execution__pb2.ExecutePipelineRequest.FromString,
                    response_serializer=execution__pb2.ExecutePipelineResponse.SerializeToString,
            ),
            'StreamPipeline': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPipeline,
                    request_deserializer=execution__pb2.StreamPipelineRequest.FromString,
                    response_serializer=execution__pb2.StreamPipelineResponse.SerializeToString,
            ),
            'SavePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.SavePipeline,
                    request_deserializer=execution__pb2.SavePipelineRequest.FromString,
                    response_serializer=execution__pb2.SavePipelineResponse.SerializeToString,
            ),
            'LoadPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadPipeline,
                    request_deserializer=execution__pb2.LoadPipelineRequest.FromString,
                    response_serializer=execution__pb2.LoadPipelineResponse.SerializeToString,
            ),
            'ListStoredPipelines': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStoredPipelines,
                    request_deserializer=execution__pb2.ListStoredPipelinesRequest.FromString,
                    response_serializer=execution__pb2.ListStoredPipelinesResponse.SerializeToString,
            ),
            'ClonePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.ClonePipeline,
                    request_deserializer=execution__pb2.ClonePipelineRequest.FromString,
                    response_serializer=execution__pb2.ClonePipelineResponse.SerializeToString,
            ),
            'SaveNode': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveNode,
                    request_deserializer=execution__pb2.SaveNodeRequest.FromString,
                    response_serializer=execution__pb2.SaveNodeResponse.SerializeToString,
            ),
            'LoadNode': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadNode,
                    request_deserializer=execution__pb2.LoadNodeRequest.FromString,
                    response_serializer=execution__pb2.LoadNodeResponse.SerializeToString,
            ),
            'ListStoredNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStoredNodes,
                    request_deserializer=execution__pb2.ListStoredNodesRequest.FromString,
                    response_serializer=execution__pb2.ListStoredNodesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remotemedia.execution.RemoteExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('remotemedia.execution.RemoteExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteExecutionService(object):
    """Remote Execution Service
    Provides secure, sandboxed execution of processing nodes
    """

    @staticmethod
    def ExecuteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/ExecuteNode',
            execution__pb2.ExecuteNodeRequest.SerializeToString,
            execution__pb2.ExecuteNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCustomTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/ExecuteCustomTask',
            execution__pb2.ExecuteCustomTaskRequest.SerializeToString,
            execution__pb2.ExecuteCustomTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamNode(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/remotemedia.execution.RemoteExecutionService/StreamNode',
            execution__pb2.StreamData.SerializeToString,
            execution__pb2.StreamData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamObject(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/remotemedia.execution.RemoteExecutionService/StreamObject',
            execution__pb2.StreamObjectRequest.SerializeToString,
            execution__pb2.StreamObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteObjectMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/ExecuteObjectMethod',
            execution__pb2.ExecuteObjectMethodRequest.SerializeToString,
            execution__pb2.ExecuteObjectMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/GetStatus',
            execution__pb2.StatusRequest.SerializeToString,
            execution__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/ListNodes',
            execution__pb2.ListNodesRequest.SerializeToString,
            execution__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitGenerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/InitGenerator',
            execution__pb2.InitGeneratorRequest.SerializeToString,
            execution__pb2.InitGeneratorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/GetNextBatch',
            execution__pb2.GetNextBatchRequest.SerializeToString,
            execution__pb2.GetNextBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseGenerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/CloseGenerator',
            execution__pb2.CloseGeneratorRequest.SerializeToString,
            execution__pb2.CloseGeneratorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportTypeScriptDefinitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/ExportTypeScriptDefinitions',
            execution__pb2.ExportTypeScriptRequest.SerializeToString,
            execution__pb2.ExportTypeScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/RegisterPipeline',
            execution__pb2.RegisterPipelineRequest.SerializeToString,
            execution__pb2.RegisterPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/UnregisterPipeline',
            execution__pb2.UnregisterPipelineRequest.SerializeToString,
            execution__pb2.UnregisterPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPipelines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/ListPipelines',
            execution__pb2.ListPipelinesRequest.SerializeToString,
            execution__pb2.ListPipelinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPipelineInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/GetPipelineInfo',
            execution__pb2.GetPipelineInfoRequest.SerializeToString,
            execution__pb2.GetPipelineInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/ExecutePipeline',
            execution__pb2.ExecutePipelineRequest.SerializeToString,
            execution__pb2.ExecutePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPipeline(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/remotemedia.execution.RemoteExecutionService/StreamPipeline',
            execution__pb2.StreamPipelineRequest.SerializeToString,
            execution__pb2.StreamPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SavePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/SavePipeline',
            execution__pb2.SavePipelineRequest.SerializeToString,
            execution__pb2.SavePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/LoadPipeline',
            execution__pb2.LoadPipelineRequest.SerializeToString,
            execution__pb2.LoadPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStoredPipelines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/ListStoredPipelines',
            execution__pb2.ListStoredPipelinesRequest.SerializeToString,
            execution__pb2.ListStoredPipelinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClonePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/ClonePipeline',
            execution__pb2.ClonePipelineRequest.SerializeToString,
            execution__pb2.ClonePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/SaveNode',
            execution__pb2.SaveNodeRequest.SerializeToString,
            execution__pb2.SaveNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/LoadNode',
            execution__pb2.LoadNodeRequest.SerializeToString,
            execution__pb2.LoadNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStoredNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotemedia.execution.RemoteExecutionService/ListStoredNodes',
            execution__pb2.ListStoredNodesRequest.SerializeToString,
            execution__pb2.ListStoredNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
