# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from remotemedia.protos import control_pb2 as control__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PipelineControlStub(object):
    """============================================================================
    Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Attach = channel.stream_stream(
                '/remotemedia.v1.PipelineControl/Attach',
                request_serializer=control__pb2.ControlFrame.SerializeToString,
                response_deserializer=control__pb2.ControlEvent.FromString,
                _registered_method=True)


class PipelineControlServicer(object):
    """============================================================================
    Service
    ============================================================================

    """

    def Attach(self, request_iterator, context):
        """Open a control-plane attach to an existing session. The first frame
        the client sends MUST be a `Hello`. The server streams `ControlEvent`s
        back until the session terminates or the client closes the stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Attach': grpc.stream_stream_rpc_method_handler(
                    servicer.Attach,
                    request_deserializer=control__pb2.ControlFrame.FromString,
                    response_serializer=control__pb2.ControlEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remotemedia.v1.PipelineControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('remotemedia.v1.PipelineControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineControl(object):
    """============================================================================
    Service
    ============================================================================

    """

    @staticmethod
    def Attach(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/remotemedia.v1.PipelineControl/Attach',
            control__pb2.ControlFrame.SerializeToString,
            control__pb2.ControlEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
